<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Natural-Language-Processing/blob/main/Word_Embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

**One Hot Representation**

In [7]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[3502, 313, 8182, 7407], [3502, 313, 8182, 1850], [3502, 3022, 8182, 907], [5903, 6702, 4575, 7007, 777], [5903, 6702, 4575, 7007, 2822], [3208, 3502, 8749, 8182, 8793], [2564, 4234, 8198, 7007]]


**Word Embedding Representation**

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,maxlen=sent_length,padding='pre')
print(embedded_docs)

[[   0    0    0    0 3502  313 8182 7407]
 [   0    0    0    0 3502  313 8182 1850]
 [   0    0    0    0 3502 3022 8182  907]
 [   0    0    0 5903 6702 4575 7007  777]
 [   0    0    0 5903 6702 4575 7007 2822]
 [   0    0    0 3208 3502 8749 8182 8793]
 [   0    0    0    0 2564 4234 8198 7007]]


In [11]:
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403
    0.02213112  0.0277811  -0.04952705  0.02351796 -0.0328116 ]
  [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403
    0.02213112  0.0277811  -0.04952705  0.02351796 -0.0328116 ]
  [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403
    0.02213112  0.0277811  -0.04952705  0.02351796 -0.0328116 ]
  [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403
    0.02213112  0.0277811  -0.04952705  0.02351796 -0.0328116 ]
  [ 0.0061357   0.01315385 -0.03254161 -0.03592064  0.01771747
   -0.01469436  0.03668236  0.03089457  0.04187758 -0.04057521]
  [ 0.0376053  -0.04397857  0.00888331  0.04417999 -0.03675403
    0.0238697   0.04194683  0.02184054  0.0290766   0.04720719]
  [ 0.02884183  0.0468854   0.04460232  0.02700948  0.03949049
    0.02843196  0.00533801 -0.02415124  0.00805116 -0.0339001 ]
  [ 0.03260583  0.029161   -0.04922037  0.0258775  -0.0145913
   -0.04692687 -0.01763054 -0.00975519  0.0317574

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403  0.02213112
   0.0277811  -0.04952705  0.02351796 -0.0328116 ]
 [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403  0.02213112
   0.0277811  -0.04952705  0.02351796 -0.0328116 ]
 [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403  0.02213112
   0.0277811  -0.04952705  0.02351796 -0.0328116 ]
 [ 0.03453742  0.03764652  0.00466846  0.02580489  0.01784403  0.02213112
   0.0277811  -0.04952705  0.02351796 -0.0328116 ]
 [ 0.0061357   0.01315385 -0.03254161 -0.03592064  0.01771747 -0.01469436
   0.03668236  0.03089457  0.04187758 -0.04057521]
 [ 0.0376053  -0.04397857  0.00888331  0.04417999 -0.03675403  0.0238697
   0.04194683  0.02184054  0.0290766   0.04720719]
 [ 0.02884183  0.0468854   0.04460232  0.02700948  0.03949049  0.02843196
   0.00533801 -0.02415124  0.00805116 -0.0339001 ]
 [ 0.03260583  0.029161   -0.04922037  0.0258775  -0.0145913  -0.04692687
  -0.01763054 -0.00975519  0.03175746  0.00812911]]
